### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected a dependency for the `laravel/framework`. Unless you have a special requirement for depending on the entire Laravel framework, it's recommended to add dependencies for the specific `illuminate` packages instead.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/tallstackui/tallstackui/pull/332/commits/92f4762e5fffac59b3daaf1cd741410526a507e9?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/tallstackui.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "tallstackui/tallstackui": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by devajmeireles** [comment]
We need to wait for the official Laravel `11.x` tag to validate all our tests using Github Actions.

**Comment by jasonmccreary** [comment]
You can point to `dev-master` to get your build running against Laravel 11.

**Comment by devajmeireles** [comment]
> You can point to `dev-master` to get your build running against Laravel 11.

Hey, Jason! Thanks for your answer. Since Laravel 11 will be released on 12th March, I'd prefer to wait for the official 11.x tag. Super appreciate your help on this. Laravel Shift always saves our lives! :)

**Pull request merged**
