### PR TITLE
Class personalisations

### PR DESCRIPTION
**Pull request by crossplatformconsulting**
### Checklist:

- [x] I read the [CONTRIBUTION GUIDE](https://tallstackui.com/docs/contribution)
- [x] I created a new branch on my fork for this pull request 
- [x] I ensure that the current tests are passing
- [ ] I added tests that prove this pull request is working

### What:

- [ ] Feature
- [x] Enhancements
- [ ] Bugfix

### Description:
Add Soft Personalization key for table.tr

### CODE REVIEW

**Comment by devajmeireles** [comment]
While there is no description in this PR, I understand the intent of this PR. I agree with the idea of ​​creating a new soft personalization key, but I disagree with passing custom classes directly using `addClass`. I'd merge this if you adapted the PR by just inserting the new soft personalization key.

**Comment by crossplatformconsulting** [comment]
That's on me. i renamed the original branch and it lost the original PR - i made a new one in haste. 
That makes sense, i could just apply that class with CSS specific column stuff. Will adjust.

**Comment by crossplatformconsulting** [comment]
hi, just checking if the changes were ok?

**Comment by devajmeireles** [comment]
> hi, just checking if the changes were ok?

Yes! Just holding a while for I'm working on v2 stuff.

**Review by devajmeireles — APPROVED** [review]

**Pull request merged**
